<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = $vendorDir;

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'OCA\\Sharing\\AppInfo\\Application' => $baseDir . '/../lib/AppInfo/Application.php',
    'OCA\\Sharing\\Capabilities' => $baseDir . '/../lib/Capabilities.php',
    'OCA\\Sharing\\Command\\Create' => $baseDir . '/../lib/Command/Create.php',
    'OCA\\Sharing\\Command\\Delete' => $baseDir . '/../lib/Command/Delete.php',
    'OCA\\Sharing\\Command\\Get' => $baseDir . '/../lib/Command/Get.php',
    'OCA\\Sharing\\Command\\Update' => $baseDir . '/../lib/Command/Update.php',
    'OCA\\Sharing\\Controller\\ApiV1Controller' => $baseDir . '/../lib/Controller/ApiV1Controller.php',
    'OCA\\Sharing\\Migration\\Version1000Date20250929161325' => $baseDir . '/../lib/Migration/Version1000Date20250929161325.php',
    'OCA\\Sharing\\ResponseDefinitions' => $baseDir . '/../lib/ResponseDefinitions.php',
);
