<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitSharing
{
    public static $prefixLengthsPsr4 = array (
        'O' =>
        array (
            'OCA\\Sharing\\' => 12,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'OCA\\Sharing\\' =>
        array (
            0 => __DIR__ . '/..' . '/../lib',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'OCA\\Sharing\\AppInfo\\Application' => __DIR__ . '/..' . '/../lib/AppInfo/Application.php',
        'OCA\\Sharing\\Capabilities' => __DIR__ . '/..' . '/../lib/Capabilities.php',
        'OCA\\Sharing\\Command\\Create' => __DIR__ . '/..' . '/../lib/Command/Create.php',
        'OCA\\Sharing\\Command\\Delete' => __DIR__ . '/..' . '/../lib/Command/Delete.php',
        'OCA\\Sharing\\Command\\Get' => __DIR__ . '/..' . '/../lib/Command/Get.php',
        'OCA\\Sharing\\Command\\Update' => __DIR__ . '/..' . '/../lib/Command/Update.php',
        'OCA\\Sharing\\Controller\\ApiV1Controller' => __DIR__ . '/..' . '/../lib/Controller/ApiV1Controller.php',
        'OCA\\Sharing\\Migration\\Version1000Date20250929161325' => __DIR__ . '/..' . '/../lib/Migration/Version1000Date20250929161325.php',
        'OCA\\Sharing\\ResponseDefinitions' => __DIR__ . '/..' . '/../lib/ResponseDefinitions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitSharing::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitSharing::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitSharing::$classMap;

        }, null, ClassLoader::class);
    }
}
